accent = "#1a6d9e"
cursor = "#3d4c53"
foreground = "#3d4c53"
background = "#fdf6e3"
selection_foreground = "#fdf6e3"
selection_background = "#3d4c53"

color0 = "#e0dcc7"
color1 = "#c03c39"
color2 = "#5c7a0c"
color3 = "#b08500"
color4 = "#1a6d9e"
color5 = "#b84d94"
color6 = "#1e7d5a"
color7 = "#3d4c53"
color8 = "#d8d3ba"
color9 = "#c03c39"
color10 = "#5c7a0c"
color11 = "#b08500"
color12 = "#1a6d9e"
color13 = "#b84d94"
color14 = "#1e7d5a"
color15 = "#3d4c53"
